# Generated by Django 4.2.7 on 2024-02-07 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0004_rename_last_name_employee_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=127, unique=True)),
                ('person_in_charge', models.CharField(max_length=127, null=True)),
                ('pic_email', models.CharField(max_length=127, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=127, null=True)),
                ('create_date', models.DateField(null=True)),
                ('create_person', models.CharField(max_length=127)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accounttype', to_field='account_type')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
