# Generated by Django 4.2.7 on 2024-02-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='updater',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
