# Generated by Django 4.2.7 on 2023-12-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=127)),
                ('asset_label', models.CharField(max_length=127)),
                ('brand', models.CharField(max_length=127)),
                ('model', models.CharField(max_length=127, null=True)),
                ('serial_number', models.CharField(max_length=127)),
                ('purchase_date', models.DateTimeField(null=True)),
                ('purchase_cost', models.DecimalField(decimal_places=3, max_digits=9)),
                ('status', models.CharField(max_length=15, null=True)),
                ('processor', models.CharField(max_length=127, null=True)),
                ('ram', models.IntegerField(null=True)),
                ('storage', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=127)),
                ('asset_label', models.CharField(max_length=127)),
                ('brand', models.CharField(max_length=127)),
                ('model', models.CharField(max_length=127, null=True)),
                ('serial_number', models.CharField(max_length=127)),
                ('purchase_date', models.DateTimeField(null=True)),
                ('purchase_cost', models.DecimalField(decimal_places=3, max_digits=9)),
                ('status', models.CharField(max_length=15, null=True)),
                ('screen_size', models.IntegerField(null=True)),
                ('resolution', models.CharField(max_length=63)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
