# Generated by Django 4.2.7 on 2024-01-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_alter_laptop_ram_alter_laptop_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='asset_label',
            field=models.CharField(max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='asset_label',
            field=models.CharField(max_length=127, unique=True),
        ),
    ]
