# Generated by Django 4.2.7 on 2024-02-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_alter_laptop_asset_label_alter_monitor_asset_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='purchase_order_number',
            field=models.CharField(max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='purchase_order_number',
            field=models.CharField(max_length=31, null=True),
        ),
    ]
