# Generated by Django 4.2.7 on 2023-11-21 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_name', models.CharField(max_length=63, null=True)),
                ('bg_manager', models.CharField(max_length=127, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bu_name', models.CharField(max_length=63, null=True)),
                ('bg_name', models.CharField(max_length=63, null=True)),
                ('bu_manager', models.CharField(max_length=127, null=True)),
                ('le_name', models.CharField(max_length=63, null=True)),
                ('bg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bu_set', to='department.businessgroup')),
            ],
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('le_name', models.CharField(max_length=63, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_code', models.CharField(max_length=31)),
                ('cc_name', models.CharField(max_length=63)),
                ('cc_manager', models.CharField(max_length=127, null=True)),
                ('bu_name', models.CharField(max_length=63, null=True)),
                ('bg_name', models.CharField(max_length=63, null=True)),
                ('le_name', models.CharField(max_length=63, null=True)),
                ('bu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cc_set', to='department.businessunit')),
            ],
        ),
        migrations.AddField(
            model_name='businessgroup',
            name='le',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bg_set', to='department.legalentity', to_field='le_name'),
        ),
    ]
