# Generated by Django 4.2.7 on 2023-12-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=31, null=True)),
                ('user', models.CharField(max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('memo', models.TextField(null=True)),
                ('cc_code', models.CharField(max_length=15, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
