# Generated by Django 4.2.7 on 2023-12-19 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_active'),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAssignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=31, null=True)),
                ('user', models.CharField(max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('memo', models.TextField(null=True)),
                ('employee_first_name', models.CharField(max_length=127)),
                ('employee_last_name', models.CharField(max_length=127)),
                ('asset_type', models.CharField(max_length=127)),
                ('asset_serial_number', models.CharField(max_length=127)),
                ('asset_label', models.CharField(max_length=127)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
