# Generated by Django 4.2.7 on 2024-01-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_laptoplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptoplog',
            name='serial_number',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='laptoplog',
            name='asset_label',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
