# Generated by Django 4.2.7 on 2024-01-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_laptoplog_serial_number_alter_laptoplog_asset_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=31, null=True)),
                ('user', models.CharField(max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('memo', models.TextField(null=True)),
                ('asset_label', models.CharField(max_length=127, null=True)),
                ('serial_number', models.CharField(max_length=127, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
