# Generated by Django 4.2.7 on 2024-02-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0009_employeelog_department_employeelog_employee_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=31, null=True)),
                ('user', models.CharField(max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('memo', models.TextField(null=True)),
                ('target_user', models.CharField(max_length=127)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
