# Generated by Django 4.2.7 on 2024-03-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0011_assetlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetassignlog',
            old_name='employee_first_name',
            new_name='employee_name',
        ),
        migrations.RemoveField(
            model_name='assetassignlog',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='assetassignlog',
            name='employee_last_name',
        ),
        migrations.AddField(
            model_name='assetassignlog',
            name='employee_id',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
