# Generated by Django 4.2.7 on 2024-03-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0012_rename_employee_first_name_assetassignlog_employee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetassignlog',
            name='employee_name',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
