# Generated by Django 4.2.7 on 2023-12-19 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=127)),
                ('middle_name', models.CharField(max_length=127)),
                ('Last_name', models.CharField(max_length=127)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('leave_date', models.DateTimeField(auto_now_add=True)),
                ('supervisor', models.CharField(max_length=127)),
                ('ms_account', models.CharField(max_length=255)),
                ('adp_account', models.CharField(max_length=255)),
                ('redmine_account', models.CharField(max_length=255)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.costcenter')),
                ('laptop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset.laptop')),
                ('monitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset.monitor')),
            ],
        ),
    ]
