# Generated by Django 4.2.7 on 2024-02-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employee_id_employee_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='employee',
            name='leave_date',
            field=models.DateTimeField(null=True),
        ),
    ]
