# Generated by Django 4.2.7 on 2024-02-11 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_preferred_name_alter_employee_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='adp_account',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ms_account',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='redmine_account',
        ),
    ]
