# Generated by Django 4.2.7 on 2024-03-02 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_employee_adp_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=127)),
                ('asset_label', models.CharField(max_length=127)),
                ('asset_serial_number', models.CharField(max_length=127)),
                ('asset_model', models.CharField(max_length=127)),
                ('assign_date', models.DateTimeField(auto_now_add=True)),
                ('assign_person', models.CharField(max_length=127)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
