# Generated by Django 4.2.7 on 2024-03-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employee_email_employeeasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeasset',
            name='asset_brand',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
