# Generated by Django 4.2.7 on 2024-03-03 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_employeeasset_asset_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='laptop',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='monitor',
        ),
    ]
